let header = document.querySelector(`article > header`)
header.innerHTML = `Pursuit of Happiness`

let div = document.querySelector(`article > div`)
div.innerHTML = `I dream of us one day uttering those three simple words to each other. You often ask me what is it about yourself that keeps me in a trance. I finally have the time to articulate my thoughts. You believe it's solely your beauty that has me mesmerized yet I do not chase the stars with the same affection as I do you. 
My mind belonged to you the moment we first met. The way you awkwardly and confidentaly carried yourself. The way you grin ear to ear right before you poke me. The softness in your voice whenever you read. The authority in your voice as mother. Your nurturing nature as a mother. The way you're not afraid to feel. How you refuse to settle on anything less than the cupcake stage. Your sense of style. The way you don't know how to hold hands. The way you cover your mouth right before you burst our laughing. The way you tense up around crowds. The way you ease up when you drink. Your love of plants. Your love of books. Your stubborn attitude. How you turn your head away whenever your upset. How you refuse to let me put myself down. How untraditional your family is. How you seek a traditional family. The way you eat with European etiquette. The way you lean your head against me. Your competitive spirit. But most of all, no matter how life or your illness attempts to engulf you, you persist on letting the light of your love be seen.
Our history has been brief and yet forever just doesn't seem like enough time together. I wish to let my inhibitions go and let my passion for you shake me to my core. I'll continue to wait. I don't know what I was looking for when I found you but a lifetime of events caused our paths to collide. I miss you.`

//test
